name: marlin_auto_build

on:
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'
  # trigger every night at 03:30
  #schedule:
  #  - cron:  '30 3 * * *'
  workflow_dispatch:

jobs:
  create_builds:
    runs-on: ubuntu-latest
    steps:
      - run: rm -rf marlin_auto_build

      - name: build
        uses: zisismaras/marlin_auto_build@v1.0.12