name: marlin_auto_build

on:
 workflow_dispatch:
  inputs:
    tags:
      description: 'Test scenario tags'  
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'
  # trigger every night at 03:30
  #schedule:
  #  - cron:  '30 3 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: pavelmaca/marlin_auto_build@debug